cabal-version:      2.2
name:               structured
version:            0.1.2
synopsis:           Structure (hash) of your data types
category:           Data
description:
  Calculate the hash of a data structure.
  It can be used as a magic number for the serialization formats.
  See <https://hackage.haskell.org/package/binary-tagged binary-tagged>
  for a @binary@ bindings.

bug-reports:        https://github.com/phadej/binary-tagged/issues
author:             Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer:         Oleg Grenrus <oleg.grenrus@iki.fi>
license:            BSD-3-Clause
license-file:       LICENSE
build-type:         Simple
extra-source-files: CHANGELOG.md
tested-with:
  GHC ==8.6.5
   || ==8.8.4
   || ==8.10.7
   || ==9.0.2
   || ==9.2.8
   || ==9.4.8
   || ==9.6.7
   || ==9.8.4
   || ==9.10.3
   || ==9.12.4
   || ==9.14.1

source-repository head
  type:     git
  location: https://github.com/phadej/binary-tagged
  subdir:   structured

library
  default-language: Haskell2010
  hs-source-dirs:   src
  ghc-options:      -Wall
  exposed-modules:  Data.Structured
  exposed-modules:  Data.Structured.Internal
  other-modules:    Data.Structured.MD5

  -- Libraries bundled with GHC
  build-depends:
    , array         ^>=0.5.3.0
    , base          >=4.12.0.0  && <4.23
    , bytestring    ^>=0.10.4.0 || ^>=0.11    || ^>=0.12.0.2
    , containers    ^>=0.6.0.1  || ^>=0.7     || ^>=0.8
    , text          ^>=1.2.3.0  || ^>=2.0     || ^>=2.1
    , transformers  ^>=0.5.6.2  || ^>=0.6.1.0

  -- other dependencies
  build-depends:
    , aeson                 ^>=2.2.3.0  || ^>=2.3.0.0
    , scientific            ^>=0.3.8.0
    , tagged                ^>=0.8.8
    , time-compat           ^>=1.9.7
    , unordered-containers  ^>=0.2.20
    , uuid-types            ^>=1.0.6
    , vector                ^>=0.13.1.0
